title: Xavier Quinn # your name (or website title) here
logo: "images/profile-pic(4).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst  <br><br>
  I love puzzles, music, reading, and learning new things about history  <br><br>
  xaviertquinn@gmail.com | 267 825 0722  <br><br>
  <a href="https://www.linkedin.com/in/xaviertquinn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-XNNPS19QZG # your Google Analytics tracking ID here
