title: Xavier Quinn # your name (or website title) here
logo: "https://ibb.co/vv4q01h" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst 
  I want some pizza  <br><br>
  <a href="https://www.linkedin.com/in/xaviertquinn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
